// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// internal_split_clf
DataFrame internal_split_clf(CharacterVector requests);
RcppExport SEXP webreadr_internal_split_clf(SEXP requestsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type requests(requestsSEXP);
    __result = Rcpp::wrap(internal_split_clf(requests));
    return __result;
END_RCPP
}
// internal_split_squid
DataFrame internal_split_squid(CharacterVector requests);
RcppExport SEXP webreadr_internal_split_squid(SEXP requestsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type requests(requestsSEXP);
    __result = Rcpp::wrap(internal_split_squid(requests));
    return __result;
END_RCPP
}
