# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_split <- function(requests, names) {
    .Call('webtools_internal_split', PACKAGE = 'webtools', requests, names)
}

#'@title Take vectors of IPs and X-Forwarded-For headers and produce single, normalised
#'IP addresses.
#'@description \code{normalise_ips} takes IP addresses and x_forwarded_for
#'values and, in the event that x_forwarded_for is non-null, attempts to
#'extract the "real" IP closest to the client.
#'
#'@param ip_addresses a vector of IP addresses
#'
#'@param x_forwarded_fors an equally-sized vector of X-Forwarded-For header
#'contents.
#'
#'@return a vector of IP addresses, incorporating the XFF header value
#'where appropriate
#'
#'@export
sanitise_ips <- function(ip_addresses, x_forwarded_fors) {
    .Call('webtools_sanitise_ips', PACKAGE = 'webtools', ip_addresses, x_forwarded_fors)
}

#'@title decodes a vector of URLs
#'@description Takes a vector of URLs and consistently decodes them, in
#'a vectorised way and handling out-of-range characters (unlike \code{\link{URLdecode}})).
#'
#'@param urls a vector of URLs to decode.
#'
#'@return a character vector containing the decoded versions of urls.
#'
#'@examples
#'
#'url_decode("https://en.wikipedia.org/wiki/File:Vice_City_Public_Radio_%28logo%29.jpg")
#'
#'\dontrun{
#'#A demonstrator of the contrasting behaviours around out-of-range characters
#'URLdecode("%gIL")
#'url_decode("%gIL")
#'}
#'@export
url_decode <- function(urls) {
    .Call('webtools_url_decode', PACKAGE = 'webtools', urls)
}

