# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_split_clf <- function(requests) {
    .Call('webreadr_internal_split_clf', PACKAGE = 'webreadr', requests)
}

internal_split_squid <- function(requests) {
    .Call('webreadr_internal_split_squid', PACKAGE = 'webreadr', requests)
}

